name: Deploy Obfuscated JS Only

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Obfuscate JavaScript for v1 and v2
        run: |
          npm run obfuscatev1
          npm run obfuscatev2
      
      - name: Create deployment directory
        run: |
          mkdir -p ./deploy
          
      - name: Copy only obfuscated JS
        run: |
          cp script.obf.js ./deploy/
          cp scriptv1.obf.js ./deploy/
          
      - name: Create .nojekyll file
        run: touch ./deploy/.nojekyll
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./deploy
          branch: gh-pages
          clean: true
